name: The Adventureologist
favicon: null
layout_spectrum: 0.9751841807737947
typography_spectrum: 0.41156177199445665
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6961457231082022
  lightness: 0.45386245497502387
  saturation: 0.2408376857638359
  rhythmicContrast: 0.28017786191776395
purpose: []
