name: The Adventureologist
favicon: null
layout_spectrum: 0.96401
typography_spectrum: 0.05156
title: 'Travel, Adventure and Exploration'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#188f8b'
    - '#feffff'
    - '#091416'
    - '#4bb5ae'
    - '#123f3e'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.28017786191776395
purpose: []
